# run arguments:
method: diffdock # the method for which to score predictions - NOTE: must be one of (`diffdock`, `fabind`, `dynamicbind`, `neuralplexer`, `rfaa`, `vina`, `ensemble`)
vina_binding_site_method: diffdock # the method to use for Vina binding site prediction - NOTE: must be one of (`diffdock`, `fabind`, `dynamicbind`, `neuralplexer`, `rfaa`, `p2rank`)
dataset: astex_diverse # the dataset to use - NOTE: must be one of (`posebusters_benchmark`, `astex_diverse`, `dockgen`, `casp15`)
repeat_index: 1 # the repeat index which was used for inference
cuda_device_index: 0 # the CUDA device index to use for inference (for all methods except AutoDock-Vina)
output_script_dir: ${oc.env:PROJECT_ROOT}/scripts/inference # the directory in which to save the output script
export_hpc_headers: false # whether to insert high-performance computing (by default, SLURM) headers into the output script
# sweep arguments:
sweep: false # whether to build all combinations of method-dataset run scripts
methods_to_sweep: [
    "diffdock",
    "fabind",
    "dynamicbind",
    "neuralplexer",
    "rfaa",
    "vina",
    "ensemble",
  ] # the methods to sweep
vina_binding_site_methods_to_sweep: ["diffdock", "p2rank"] # the Vina binding site prediction methods to sweep
datasets_to_sweep: [
    "posebusters_benchmark",
    "astex_diverse",
    "dockgen",
    "casp15",
  ] # the datasets to sweep
num_sweep_repeats: 3 # the number of repeats to run for each method-dataset sweep (if the method is a generative method)
