method: diffdock # the method for which to score predictions - NOTE: must be one of (`diffdock`, `fabind`, `dynamicbind`, `neuralplexer`, `rfaa`, `vina`, `ensemble`)
vina_binding_site_method: diffdock # the method to use for Vina binding site prediction - NOTE: must be one of (`diffdock`, `fabind`, `dynamicbind`, `neuralplexer`, `rfaa`, `p2rank`)
dataset: astex_diverse # the dataset to use - NOTE: must be one of (`posebusters_benchmark`, `astex_diverse`, `dockgen`, `casp15`)
repeat_index: 1 # the repeat index which was used for inference
num_repeats: 3 # the number of repeats to be used when building all combinations of scripts
cuda_device_index: 0 # the CUDA device index to use for inference (for all methods except AutoDock-Vina)
output_script_dir: ${oc.env:PROJECT_ROOT}/scripts/inference # the directory in which to save the output script
export_hpc_headers: false # whether to insert HPC headers into the output script
build_all_scripts: false # whether to build all combinations of scripts
