name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Mambaforge
          channels: "conda-forge, pytorch"
          python-version: ${{ matrix.python-version }}
          auto-update-conda: true
          use-mamba: true
          auto-activate-base: true
          activate-environment: ""
      - name: Install dependencies
        run: |
          mamba install -c conda-forge -n base -y openff-amber-ff-ports openff-forcefields openff-interchange openff-interchange-base openff-models openff-toolkit openff-toolkit-base openff-units openff-utilities openmm openmmforcefields && pip install -e . && pip install -r docs/.docs.requirements
      - name: Sphinx build
        run: |
          conda activate base && rm -rf docs/build/ && sphinx-build docs/source/ docs/build/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/
          force_orphan: true
